# Regressao usando base de Carros usados

In [ ]:
#Importar dados essenciais
import pandas as pd
import numpy as np

from google.colab import drive
drive.mount('/content/drive/')

dataset = pd.read_csv('/content/drive/My Drive/CursoIA/RegressaoCarrosUsados/autos.csv', encoding='ISO-8859-1')
dataset

Drive already mounted at /content/drive/; to attempt to forcibly remount, call drive.mount("/content/drive/", force_remount=True).

,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
0,2016-03-24 11:52:17,Golf_3_1.6,privat,Angebot,480,test,NaN,1993,manuell,0,golf,150000,0,benzin,volkswagen,NaN,2016-03-24 00:00:00,0,70435,2016-04-07 03:16:57
1,2016-03-24 10:58:45,A5_Sportback_2.7_Tdi,privat,Angebot,18300,test,coupe,2011,manuell,190,NaN,125000,5,diesel,audi,ja,2016-03-24 00:00:00,0,66954,2016-04-07 01:46:50
2,2016-03-14 12:52:21,"Jeep_Grand_Cherokee_""Overland""",privat,Angebot,9800,test,suv,2004,automatik,163,grand,125000,8,diesel,jeep,NaN,2016-03-14 00:00:00,0,90480,2016-04-05 12:47:46
3,2016-03-17 16:54:04,GOLF_4_1_4__3TÃœRER,privat,Angebot,1500,test,kleinwagen,2001,manuell,75,golf,150000,6,benzin,volkswagen,nein,2016-03-17 00:00:00,0,91074,2016-03-17 17:40:17
4,2016-03-31 17:25:20,Skoda_Fabia_1.4_TDI_PD_Classic,privat,Angebot,3600,test,kleinwagen,2008,manuell,69,fabia,90000,7,diesel,skoda,nein,2016-03-31 00:00:00,0,60437,2016-04-06 10:17:21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371523,2016-03-14 17:48:27,Suche_t4___vito_ab_6_sitze,privat,Angebot,2200,test,NaN,2005,NaN,0,NaN,20000,1,NaN,sonstige_autos,NaN,2016-03-14 00:00:00,0,39576,2016-04-06 00:46:52
371524,2016-03-05 19:56:21,Smart_smart_leistungssteigerung_100ps,privat,Angebot,1199,test,cabrio,2000,automatik,101,fortwo,125000,3,benzin,smart,nein,2016-03-05 00:00:00,0,26135,2016-03-11 18:17:12
371525,2016-03-19 18:57:12,Volkswagen_Multivan_T4_TDI_7DC_UY2,privat,Angebot,9200,test,bus,1996,manuell,102,transporter,150000,3,diesel,volkswagen,nein,2016-03-19 00:00:00,0,87439,2016-04-07 07:15:26
371526,2016-03-20 19:41:08,VW_Golf_Kombi_1_9l_TDI,privat,Angebot,3400,test,kombi,2002,manuell,100,golf,150000,6,diesel,volkswagen,NaN,2016-03-20 00:00:00,0,40764,2016-03-24 12:45:21
371527,2016-03-07 19:39:19,BMW_M135i_vollausgestattet_NP_52.720____Euro,privat,Angebot,28990,control,limousine,2013,manuell,320,m_reihe,50000,8,benzin,bmw,nein,2016-03-07 00:00:00,0,73326,2016-03-22 03:17:10

In [ ]:
#Removendo colunas de dataset que nÃ£o tem relaÃ§Ã£o com o preÃ§o do VeÃ­culo

dataset = dataset.drop('dateCrawled', axis=1)
dataset = dataset.drop('dateCreated', axis=1)
dataset = dataset.drop('postalCode', axis=1)
dataset = dataset.drop('nrOfPictures', axis=1)
dataset = dataset.drop('lastSeen', axis=1)

In [ ]:
#Pelo motivo de haver vÃ¡rios nomes, vamos remover a coluna nome
dataset['name'].value_counts()

dataset = dataset.drop('name', axis=1)

In [ ]:
#Pelo motivo de haver counas ainda que nÃ£o tem muito impacto no nome, vamos remover estas colunas
dataset = dataset.drop('seller', axis=1)
dataset = dataset.drop('offerType', axis=1)

In [ ]:
#Agora vamos prÃ©-processar e remover valores inconsistentes
inconsistent = dataset.loc[dataset.price <=10]
print(len(inconsistent))

dataset = dataset.loc[dataset.price>10]

print(len(dataset))

inconsistent = dataset.loc[dataset.price>350000]
print(len(inconsistent))

dataset = dataset.loc[dataset.price<350000]
print(len(dataset))

12118
359410
115
359291

In [ ]:
#Removendo registros NAN
print(dataset['vehicleType'].value_counts()) #limousine
print(dataset['gearbox'].value_counts()) #manuell
print(dataset['model'].value_counts()) #golf
print(dataset['fuelType'].value_counts()) #benzin
print(dataset['notRepairedDamage'].value_counts()) #nein

values = {'vehicleType':'limousine',
          'gearbox':'manuell',
          'model':'golf',
          'fuelType':'benzin',
          'notRepairedDamage':'nein'}
dataset = dataset.fillna(value = values)

print(dataset)

limousine     93614
kleinwagen    78014
kombi         65921
bus           29699
cabrio        22509
coupe         18386
suv           14477
andere         3125
Name: vehicleType, dtype: int64
manuell      266547
automatik     75508
Name: gearbox, dtype: int64
golf               28989
andere             25560
3er                19905
polo               12604
corsa              12149
                   ...
serie_2                8
rangerover             6
serie_3                3
serie_1                1
discovery_sport        1
Name: model, Length: 251, dtype: int64
benzin     217582
diesel     106002
lpg          5222
cng           557
hybrid        271
andere        165
elektro       101
Name: fuelType, dtype: int64
nein    259301
ja       34004
Name: notRepairedDamage, dtype: int64
        price   abtest vehicleType  yearOfRegistration    gearbox  powerPS  \
0         480     test   limousine                1993    manuell        0
1       18300     test       coupe                2011    manuell      190
2        9800     test         suv                2004  automatik      163
3        1500     test  kleinwagen                2001    manuell       75
4        3600     test  kleinwagen                2008    manuell       69
...       ...      ...         ...                 ...        ...      ...
371523   2200     test   limousine                2005    manuell        0
371524   1199     test      cabrio                2000  automatik      101
371525   9200     test         bus                1996    manuell      102
371526   3400     test       kombi                2002    manuell      100
371527  28990  control   limousine                2013    manuell      320

              model  kilometer  monthOfRegistration fuelType           brand  \
0              golf     150000                    0   benzin      volkswagen
1              golf     125000                    5   diesel            audi
2             grand     125000                    8   diesel            jeep
3              golf     150000                    6   benzin      volkswagen
4             fabia      90000                    7   diesel           skoda
...             ...        ...                  ...      ...             ...
371523         golf      20000                    1   benzin  sonstige_autos
371524       fortwo     125000                    3   benzin           smart
371525  transporter     150000                    3   diesel      volkswagen
371526         golf     150000                    6   diesel      volkswagen
371527      m_reihe      50000                    8   benzin             bmw

       notRepairedDamage
0                   nein
1                     ja
2                   nein
3                   nein
4                   nein
...                  ...
371523              nein
371524              nein
371525              nein
371526              nein
371527              nein

[359291 rows x 12 columns]

In [ ]:
#Dividindo previsores e preÃ§o

previsores = dataset.iloc[:, 1:13].values
preco_real = dataset.iloc[:, 0].values

In [ ]:
#Importando Label Encoder

from sklearn.preprocessing import LabelEncoder

labelEncoder_previsores =  LabelEncoder()

previsores[:,0] = labelEncoder_previsores.fit_transform(previsores[:,0])
previsores[:,1] = labelEncoder_previsores.fit_transform(previsores[:,1])
previsores[:,3] = labelEncoder_previsores.fit_transform(previsores[:,3])
previsores[:,5] = labelEncoder_previsores.fit_transform(previsores[:,5])
previsores[:,8] = labelEncoder_previsores.fit_transform(previsores[:,8])
previsores[:,9] = labelEncoder_previsores.fit_transform(previsores[:,9])
previsores[:,10] = labelEncoder_previsores.fit_transform(previsores[:,10])

print(previsores[0])

[1 6 1993 1 0 118 150000 0 1 38 1]

In [ ]:
#Importando OneHotEncoder

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

columnTransformer = ColumnTransformer([('encoder', OneHotEncoder(), [0,1,3,5,8,9,10])],     remainder='passthrough')
previsores=columnTransformer.fit_transform(previsores).toarray()

previsores

array([[0.00e+00, 1.00e+00, 0.00e+00, ..., 0.00e+00, 1.50e+05, 0.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, ..., 1.90e+02, 1.25e+05, 5.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, ..., 1.63e+02, 1.25e+05, 8.00e+00],
       ...,
       [0.00e+00, 1.00e+00, 0.00e+00, ..., 1.02e+02, 1.50e+05, 3.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, ..., 1.00e+02, 1.50e+05, 6.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, ..., 3.20e+02, 5.00e+04, 8.00e+00]])

In [ ]:
# Hora de criar a rede neural
from keras.models import Sequential
from keras.layers import Dense

regressor = Sequential()

regressor.add(Dense(units = 158, activation = 'relu', input_dim = 316))
regressor.add(Dense(units = 158, activation = 'relu'))
regressor.add(Dense(units = 1, activation = 'linear'))
regressor.compile(loss = 'mean_absolute_error',
                  optimizer = 'adam',
                  metrics = ['mean_absolute_error'])

regressor.fit(previsores, preco_real, batch_size = 300, epochs = 100)

Epoch 1/100
1198/1198 [==============================] - 15s 12ms/step - loss: 3913.2468 - mean_absolute_error: 3913.2468
Epoch 2/100
1198/1198 [==============================] - 8s 7ms/step - loss: 3329.5142 - mean_absolute_error: 3329.5142
Epoch 3/100
1198/1198 [==============================] - 10s 8ms/step - loss: 3054.5605 - mean_absolute_error: 3054.5605
Epoch 4/100
1198/1198 [==============================] - 10s 8ms/step - loss: 2896.7996 - mean_absolute_error: 2896.7996
Epoch 5/100
1198/1198 [==============================] - 8s 7ms/step - loss: 2802.0957 - mean_absolute_error: 2802.0957
Epoch 6/100
1198/1198 [==============================] - 10s 8ms/step - loss: 2759.6814 - mean_absolute_error: 2759.6814
Epoch 7/100
1198/1198 [==============================] - 8s 7ms/step - loss: 2710.8071 - mean_absolute_error: 2710.8071
Epoch 8/100
1198/1198 [==============================] - 10s 8ms/step - loss: 2679.5710 - mean_absolute_error: 2679.5706
Epoch 9/100
1198/1198 [==============================] - 10s 8ms/step - loss: 2642.7996 - mean_absolute_error: 2642.7996
Epoch 10/100
1198/1198 [==============================] - 9s 7ms/step - loss: 2609.0151 - mean_absolute_error: 2609.0151
Epoch 11/100
1198/1198 [==============================] - 10s 8ms/step - loss: 2568.9438 - mean_absolute_error: 2568.9438
Epoch 12/100
1198/1198 [==============================] - 9s 7ms/step - loss: 2538.8423 - mean_absolute_error: 2538.8423
Epoch 13/100
1198/1198 [==============================] - 9s 7ms/step - loss: 2521.0273 - mean_absolute_error: 2521.0273
Epoch 14/100
1198/1198 [==============================] - 10s 8ms/step - loss: 2487.9590 - mean_absolute_error: 2487.9590
Epoch 15/100
1198/1198 [==============================] - 8s 6ms/step - loss: 2483.3970 - mean_absolute_error: 2483.3970
Epoch 16/100
1198/1198 [==============================] - 10s 8ms/step - loss: 2473.3411 - mean_absolute_error: 2473.3411
Epoch 17/100
1198/1198 [==============================] - 9s 7ms/step - loss: 2446.5142 - mean_absolute_error: 2446.5142
Epoch 18/100
1198/1198 [==============================] - 8s 7ms/step - loss: 2447.6958 - mean_absolute_error: 2447.6958
Epoch 19/100
1198/1198 [==============================] - 9s 8ms/step - loss: 2421.7329 - mean_absolute_error: 2421.7329
Epoch 20/100
1198/1198 [==============================] - 8s 6ms/step - loss: 2414.3984 - mean_absolute_error: 2414.3984
Epoch 21/100
1198/1198 [==============================] - 10s 8ms/step - loss: 2409.1785 - mean_absolute_error: 2409.1785
Epoch 22/100
1198/1198 [==============================] - 8s 7ms/step - loss: 2399.8499 - mean_absolute_error: 2399.8499
Epoch 23/100
1198/1198 [==============================] - 9s 7ms/step - loss: 2408.9385 - mean_absolute_error: 2408.9385
Epoch 24/100
1198/1198 [==============================] - 10s 8ms/step - loss: 2387.2449 - mean_absolute_error: 2387.2449
Epoch 25/100
1198/1198 [==============================] - 8s 7ms/step - loss: 2396.7837 - mean_absolute_error: 2396.7837
Epoch 26/100
1198/1198 [==============================] - 9s 8ms/step - loss: 2392.3091 - mean_absolute_error: 2392.3093
Epoch 27/100
1198/1198 [==============================] - 9s 7ms/step - loss: 2379.0632 - mean_absolute_error: 2379.0632
Epoch 28/100
1198/1198 [==============================] - 9s 7ms/step - loss: 2380.0312 - mean_absolute_error: 2380.0312
Epoch 29/100
1198/1198 [==============================] - 10s 8ms/step - loss: 2364.6538 - mean_absolute_error: 2364.6538
Epoch 30/100
1198/1198 [==============================] - 8s 7ms/step - loss: 2371.6040 - mean_absolute_error: 2371.6040
Epoch 31/100
1198/1198 [==============================] - 10s 8ms/step - loss: 2366.1367 - mean_absolute_error: 2366.1367
Epoch 32/100
1198/1198 [==============================] - 10s 9ms/step - loss: 2360.2029 - mean_absolute_error: 2360.2029
Epoch 33/100
1198/1198 [==============================] - 9s 7ms/step - loss: 2353.4844 - mean_absolute_error: 2353.4844
Epoch 34/100
1198/1198 [==============================] - 10s 8ms/step - loss: 2355.9568 - mean_absolute_error: 2355.9568
Epoch 35/100
1198/1198 [==============================] - 9s 7ms/step - loss: 2341.6035 - mean_absolute_error: 2341.6030
Epoch 36/100
1198/1198 [==============================] - 9s 7ms/step - loss: 2344.8259 - mean_absolute_error: 2344.8259
Epoch 37/100
1198/1198 [==============================] - 11s 9ms/step - loss: 2339.5413 - mean_absolute_error: 2339.5413
Epoch 38/100
1198/1198 [==============================] - 9s 8ms/step - loss: 2345.0127 - mean_absolute_error: 2345.0127
Epoch 39/100
1198/1198 [==============================] - 10s 8ms/step - loss: 2333.9629 - mean_absolute_error: 2333.9626
Epoch 40/100
1198/1198 [==============================] - 10s 8ms/step - loss: 2328.9421 - mean_absolute_error: 2328.9421
Epoch 41/100
1198/1198 [==============================] - 8s 6ms/step - loss: 2321.7134 - mean_absolute_error: 2321.7134
Epoch 42/100
1198/1198 [==============================] - 10s 8ms/step - loss: 2331.4207 - mean_absolute_error: 2331.4207
Epoch 43/100
1198/1198 [==============================] - 10s 8ms/step - loss: 2334.0237 - mean_absolute_error: 2334.0237
Epoch 44/100
1198/1198 [==============================] - 8s 7ms/step - loss: 2322.4551 - mean_absolute_error: 2322.4551
Epoch 45/100
1198/1198 [==============================] - 10s 8ms/step - loss: 2319.4253 - mean_absolute_error: 2319.4253
Epoch 46/100
1198/1198 [==============================] - 9s 8ms/step - loss: 2314.5061 - mean_absolute_error: 2314.5061
Epoch 47/100
1198/1198 [==============================] - 9s 7ms/step - loss: 2319.7979 - mean_absolute_error: 2319.7979
Epoch 48/100
1198/1198 [==============================] - 10s 8ms/step - loss: 2311.3123 - mean_absolute_error: 2311.3123
Epoch 49/100
1198/1198 [==============================] - 8s 7ms/step - loss: 2313.8242 - mean_absolute_error: 2313.8242
Epoch 50/100
1198/1198 [==============================] - 10s 8ms/step - loss: 2310.2769 - mean_absolute_error: 2310.2769
Epoch 51/100
1198/1198 [==============================] - 9s 7ms/step - loss: 2311.2544 - mean_absolute_error: 2311.2544
Epoch 52/100
1198/1198 [==============================] - 8s 7ms/step - loss: 2303.7246 - mean_absolute_error: 2303.7246
Epoch 53/100
1198/1198 [==============================] - 10s 8ms/step - loss: 2306.2646 - mean_absolute_error: 2306.2646
Epoch 54/100
1198/1198 [==============================] - 8s 6ms/step - loss: 2299.1531 - mean_absolute_error: 2299.1531
Epoch 55/100
1198/1198 [==============================] - 13s 11ms/step - loss: 2288.1919 - mean_absolute_error: 2288.1919
Epoch 56/100
1198/1198 [==============================] - 10s 8ms/step - loss: 2295.4475 - mean_absolute_error: 2295.4475
Epoch 57/100
1198/1198 [==============================] - 8s 7ms/step - loss: 2292.0466 - mean_absolute_error: 2292.0466
Epoch 58/100
1198/1198 [==============================] - 9s 8ms/step - loss: 2288.2498 - mean_absolute_error: 2288.2498
Epoch 59/100
1198/1198 [==============================] - 10s 8ms/step - loss: 2292.0015 - mean_absolute_error: 2292.0015
Epoch 60/100
1198/1198 [==============================] - 8s 6ms/step - loss: 2284.8572 - mean_absolute_error: 2284.8572
Epoch 61/100
1198/1198 [==============================] - 10s 8ms/step - loss: 2284.3716 - mean_absolute_error: 2284.3716
Epoch 62/100
1198/1198 [==============================] - 8s 7ms/step - loss: 2277.0974 - mean_absolute_error: 2277.0974
Epoch 63/100
1198/1198 [==============================] - 9s 8ms/step - loss: 2291.3052 - mean_absolute_error: 2291.3052
Epoch 64/100
1198/1198 [==============================] - 10s 8ms/step - loss: 2288.5132 - mean_absolute_error: 2288.5132
Epoch 65/100
1198/1198 [==============================] - 8s 6ms/step - loss: 2283.3372 - mean_absolute_error: 2283.3372
Epoch 66/100
1198/1198 [==============================] - 10s 8ms/step - loss: 2281.3181 - mean_absolute_error: 2281.3181
Epoch 67/100
1198/1198 [==============================] - 9s 7ms/step - loss: 2280.9897 - mean_absolute_error: 2280.9897
Epoch 68/100
1198/1198 [==============================] - 11s 9ms/step - loss: 2271.5442 - mean_absolute_error: 2271.5444
Epoch 69/100
1198/1198 [==============================] - 10s 8ms/step - loss: 2275.6609 - mean_absolute_error: 2275.6609
Epoch 70/100
1198/1198 [==============================] - 8s 7ms/step - loss: 2292.5330 - mean_absolute_error: 2292.5330
Epoch 71/100
1198/1198 [==============================] - 10s 8ms/step - loss: 2267.8293 - mean_absolute_error: 2267.8293
Epoch 72/100
1198/1198 [==============================] - 10s 8ms/step - loss: 2271.1621 - mean_absolute_error: 2271.1621
Epoch 73/100
1198/1198 [==============================] - 8s 6ms/step - loss: 2265.1973 - mean_absolute_error: 2265.1973
Epoch 74/100
1198/1198 [==============================] - 10s 8ms/step - loss: 2262.9050 - mean_absolute_error: 2262.9050
Epoch 75/100
1198/1198 [==============================] - 8s 7ms/step - loss: 2274.7852 - mean_absolute_error: 2274.7852
Epoch 76/100
1198/1198 [==============================] - 9s 8ms/step - loss: 2259.7542 - mean_absolute_error: 2259.7542
Epoch 77/100
1198/1198 [==============================] - 10s 8ms/step - loss: 2270.5361 - mean_absolute_error: 2270.5361
Epoch 78/100
1198/1198 [==============================] - 8s 7ms/step - loss: 2266.7705 - mean_absolute_error: 2266.7705
Epoch 79/100
1198/1198 [==============================] - 10s 8ms/step - loss: 2267.9634 - mean_absolute_error: 2267.9634
Epoch 80/100
1198/1198 [==============================] - 9s 7ms/step - loss: 2259.4236 - mean_absolute_error: 2259.4236
Epoch 81/100
1198/1198 [==============================] - 9s 7ms/step - loss: 2263.3777 - mean_absolute_error: 2263.3777
Epoch 82/100
1198/1198 [==============================] - 10s 8ms/step - loss: 2252.1296 - mean_absolute_error: 2252.1296
Epoch 83/100
1198/1198 [==============================] - 8s 6ms/step - loss: 2259.7700 - mean_absolute_error: 2259.7700
Epoch 84/100
1198/1198 [==============================] - 10s 8ms/step - loss: 2262.3716 - mean_absolute_error: 2262.3716
Epoch 85/100
1198/1198 [==============================] - 9s 7ms/step - loss: 2254.3208 - mean_absolute_error: 2254.3208
Epoch 86/100
1198/1198 [==============================] - 9s 7ms/step - loss: 2252.4788 - mean_absolute_error: 2252.4788
Epoch 87/100
1198/1198 [==============================] - 10s 8ms/step - loss: 2254.0425 - mean_absolute_error: 2254.0425
Epoch 88/100
1198/1198 [==============================] - 8s 6ms/step - loss: 2246.1724 - mean_absolute_error: 2246.1724
Epoch 89/100
1198/1198 [==============================] - 10s 8ms/step - loss: 2257.7886 - mean_absolute_error: 2257.7886
Epoch 90/100
1198/1198 [==============================] - 9s 7ms/step - loss: 2251.2842 - mean_absolute_error: 2251.2842
Epoch 91/100
1198/1198 [==============================] - 9s 7ms/step - loss: 2250.6138 - mean_absolute_error: 2250.6138
Epoch 92/100
1198/1198 [==============================] - 10s 8ms/step - loss: 2255.7200 - mean_absolute_error: 2255.7200
Epoch 93/100
1198/1198 [==============================] - 8s 6ms/step - loss: 2239.4390 - mean_absolute_error: 2239.4390
Epoch 94/100
1198/1198 [==============================] - 10s 8ms/step - loss: 2246.8889 - mean_absolute_error: 2246.8889
Epoch 95/100
1198/1198 [==============================] - 9s 8ms/step - loss: 2243.8135 - mean_absolute_error: 2243.8135
Epoch 96/100
1198/1198 [==============================] - 8s 7ms/step - loss: 2245.8687 - mean_absolute_error: 2245.8687
Epoch 97/100
1198/1198 [==============================] - 10s 8ms/step - loss: 2249.9116 - mean_absolute_error: 2249.9116
Epoch 98/100
1198/1198 [==============================] - 8s 7ms/step - loss: 2229.2349 - mean_absolute_error: 2229.2346
Epoch 99/100
1198/1198 [==============================] - 10s 8ms/step - loss: 2231.2839 - mean_absolute_error: 2231.2839
Epoch 100/100
1198/1198 [==============================] - 9s 8ms/step - loss: 2242.9983 - mean_absolute_error: 2242.9983

In [ ]:
# Avaliando resultados

previsoes = regressor.predict(previsores)

print(preco_real.mean())
print(previsoes.mean())

11228/11228 [==============================] - 23s 2ms/step
5916.833945186492
4746.413